// <auto-generated />
using DmhyAutoDownload.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DmhyAutoDownload.Core.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20240605072546_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DmhyAutoDownload.Core.Data.Models.Bangumi", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadedEps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryKeyWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegexGroupIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("Finished");

                    b.ToTable("Bangumis");
                });
#pragma warning restore 612, 618
        }
    }
}
