version: "3"
services:
  dmhy:
    build: .
    environment:
      - RPCADDR=http://host.docker.internal:6800/jsonrpc
      - ARIATOKEN=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - $PWD:/app/Config
    ports:
      - "80:18880"