services:
  dmhy:
    build: .
    environment:
      - RPCADDR=ws://host.docker.internal:6800/jsonrpc
      - ARIATOKEN=
    command: ["--urls", "http://0.0.0.0:8888"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./Config:/app/Config
    ports:
      - "18880:8888"
    restart: unless-stopped